### PR TITLE
Add AGMS Gateway

### PR DESCRIPTION
**Pull request by maanas**
We're with AGMS, a US-based payments and marketing technology company. Our changes add support for our AGMS Gateway (http://onlinepaymentprocessing.com, http://www.agms.com).

Thank you

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Errrr. The vendor folder shouldn't be comitted here?

**Comment by maanas** [comment]
@GrahamCampbell Can you advise me how to commit code. Should i make a repository agms-omnipay and commit code there?

**Comment by GrahamCampbell** [comment]
You probably need to maintain this repository on your own namespace for now. Then contact @philsturgeon perhapse, if you want to move it over to this organisation.

**Comment by kayladnls** [comment]
@Philsturgeon doesn't manage this repo, I do. 

I'm very happy to accept third party gateways. They should be maintained under your own namespace, in your own repo. You can make a PR to the README.md file in this repo to list your gateway as one of the supported gateways, though.

**Comment by maanas** [comment]
@philsturgeon Thank you 
@kayladnls Thank you

I m adding the code in our namespace and once it passes the travis build i will add in README.md

**Comment by philsturgeon** [comment]
I did nothing!

**Comment by GrahamCampbell** [comment]
lol

**Pull request closed without merging**
