### PR TITLE
Added note on initializing gateway parameters

### PR DESCRIPTION
**Pull request by judgej**
When using multiple gateways, initializing from data like this, rather
than through explicit driver-specific methods, can make the code a lot
more generic.

### CODE REVIEW

**Comment by judgej** [comment]
This github review process - how does it work? Is there a formal process that tracks what has been read and actions that can be ticked off? Using QMSs in the early 90s, we had a very formal process, and it involved lots of paper. I'm guessing it is something like that, but without the paper? Or maybe not? I probably just need pointing at the documentation for it, which has eluded me.

**Comment by judgej** [comment]
Just added a similar note to extend the explanation on how parameters and options can be set. Didn't realise this branch still had an outstanding PR.

**Comment by judgej** [comment]
Any objections to me merging this?

**Comment by reinink** [comment]
@judgej Honestly, I'm probably not the best person to review this PR. I've never been directly involved in this particular project. I recommend reaching out to @greydnls or @barryvdh.

**Pull request merged**
