### PR TITLE
Add createCard to the list on generally available actions

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
I'm proposing we add createCard to the list of actions as it is a key action IMHO.

The general case is that credit card details are passed in and a cardReference is returned (available by getCardReference) this can generally be used instead of credit card details in later requests.

I'm struggling a little with the Paypal Rest integration on this front as it's possible to 'create a card' when there is no card details (in the Paypal button implementation a the person is redirected to Paypal & returns with a token that if functionally equivalent to one the generic concept of 'createCard' so I though at least adding the concept into the readme is a step forwards.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
I don't even know what  fetchIssuers does :-)

**Comment by judgej** [comment]
Other gateways share PayPal's concept of a "card token" as being a generic token that gives the application the ability to use some pre-authorised payment method, whether a card, bank account, direct debit, giropay etc.

The issuers I think is a little more tricky. Issuers are about who issues a payment method, and I always thought it only makes sense in the context of a payment method, but I am not entirely sure. For example Adyen can provide a list of card types available, and for some of those card types a list of issuers. The shop can then choose which issuers to use. It may accept Visa from Bank A, or Mastercard from banks A or B, but not C. It's more common in the EC outside of the UK, so not something I am entirely familiar with, but hopefully that should give you a lead.

**Comment by aimeos** [comment]
We use @judgej card token implementation for different drivers, e.g.
- GiroCheckout: https://github.com/academe/omnipay-girocheckout#create-a-reusable-card-reference
- Datatrans: https://github.com/academe/omnipay-datatrans#getting-a-card-reference

**Comment by judgej** [comment]
Is is worth adding `updateCard` and `deleteCard` to the docs here?

See https://github.com/thephpleague/omnipay-common/blob/master/src/Common/GatewayInterface.php#L33

**Pull request merged**
