### PR TITLE
MyFatoorah OmniPay package

### PR DESCRIPTION
**Pull request by my-fatoorah**

### CODE REVIEW

**Comment by barryvdh** [comment]
This PR is incorrect, too many changes

**Comment by my-fatoorah** [comment]
Hello Barry,
Would you please clarify what is the issue exactly, and why is the PR closed?

**Comment by barryvdh** [comment]
Packages are not added in this repository. You can create your own repository and create a PR to link to it here.

**Comment by my-fatoorah** [comment]
Would you please provide me with more details, I tried to add packagist but I am not able to open a new pull request or even to open this PR! 

> Packages are not added in this repository. You can create your own repository and create a PR to link to it here.

**Pull request closed without merging**
