### PR TITLE
Add Datatrans Gateway

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
I recently implemented Datatrans for ominpay, so I wanted to share it with you and add it to the list of supported Gateways.

### CODE REVIEW

**Comment by delatbabel** [comment]
Hrm, your license is GPLv3 which I believe is incompatible with the MIT license used by the rest of the library and could be problematic for some implementations. I will ask some other team members to comment here.

**Comment by dpfaffenbauer** [comment]
We could change the license to MIT as well. I would not have any problem with that. We usually work with GPLv3 cause of our CMS system. But in this case it doesn't matter for us.

**Comment by barryvdh** [comment]
Mit would be nice, but I'm not sure its a requirement to be listed here.

**Comment by delatbabel** [comment]
OK I will go with @barryvdh 's comment -- I have merged the change to get listed here, however it would be preferable if you can change your license from GPL to MIT.  Thanks.  In terms of your CMS product it should not be an issue including an MIT library in a GPL product, it's only a problem doing it the other way around.

**Comment by dpfaffenbauer** [comment]
Thanks for merging. Just changed the license to MIT.

**Pull request merged**
