### PR TITLE
MyFatoorah

### PR DESCRIPTION
**Pull request by my-fatoorah**

### CODE REVIEW

**Comment by barryvdh** [comment]
Pleas create your own repository non Github with your gateway. You can add a link here.

**Comment by my-fatoorah** [comment]
Do you mean, I should create a new repository in GitHub??
I have created https://github.com/my-fatoorah/omnipay-myfatoorah . Is that fine now??

**Comment by barryvdh** [comment]
Yeah

**Comment by my-fatoorah** [comment]
What's next Barry?!

**Comment by barryvdh** [comment]
Add the link to the readme in this repository. Open a PR with just the link added to the table, in alphabetical order.

**Pull request closed without merging**
