### PR TITLE
Removed unnecessary dependency omnipay-tests

### PR DESCRIPTION
**Pull request by hugohenrique**
The idea of this PR is to remove the dependence on ``omnipay-tests`` repository and move the files to this codebase.

- [x] Moved ``omnipay-tests`` to codebase
- [x] Upgrade PHPunit version
- [x] Reviewed PHPunit configurations

*This should be merged to ``3.0`` branch*

### CODE REVIEW

**Comment by hugohenrique** [comment]
ping @barryvdh

**Comment by barryvdh** [comment]
What is the advantage?

**Comment by hugohenrique** [comment]
Initially:
- Remove dependency from a repository with only two test files. Leaving these in the codebase that is where it should.
- Use an autoload-dev
- Fixed configurations from PHPunit

**Comment by hugohenrique** [comment]
any news?

**Comment by delatbabel** [comment]
This actually looks OK to me. I'm not sure how many other repos there are that depend on omnipay-tests so I would leave it there but this gets my +1.  @barryvdh what do you think?

**Comment by barryvdh** [comment]
If you move the tests to autoload-dev, they will only be loaded when running tests for omnipay itself.
Other packages can't use the classes, because they will not be loaded. So I don't think this will work for other packages..

**Pull request closed without merging**
