### PR TITLE
Proposal for incoming notifications

### PR DESCRIPTION
**Pull request by sergej-koscejev**
This is a proposal to handle incoming notifications from payment gateways in a generic way (where the payment gateway notifies the merchant's backend server directly). Some gateways are currently using completePurchase() for this purpose but it's actually not its original intent, judging from official examples and documentation.

I have the PHP interface code for this ready as well, in https://github.com/sergej-koscejev/omnipay-common, but it's rather trivial so I'm only submitting the changes to the documentation at this time.

What do you think?

### CODE REVIEW

**Comment by kinosang** [comment]
Hi, all how's it going about the `processNotification()` method? I think it's necessary to use IPN from gateways to update status for billings. I want to make some changes on the PayPal library but I'm still reading the codes and haven't understood them completely.

**Comment by kayladnls** [comment]
after chewing on this for a bit would `acceptNotification()` be a better verb in your mind, @sergej-koscejev ? That doesn't necessarily indicate that it's DOING anything, anymore than accepting the notification from the gateway. 

Thoughts @barryvdh ?

**Comment by sergej-koscejev** [comment]
I think `acceptNotification()` is fine, we've been stuck on a name for far too long, let's move forward. I'm no longer active in Omnipay but I will make the change for this pull request if agreed.

**Comment by kayladnls** [comment]
agreed. Make the change, I'll merge it.

**Comment by sergej-koscejev** [comment]
Done, please review - I haven't run the tests myself since I don't even have PHP installed currently, sorry :)

**Comment by sergej-koscejev** [comment]
@kayladnls I think you should merge this as well - it's the documentation for the changes I made in the other PR.

**Pull request closed without merging**
