### PR TITLE
Added new Judo Pay gateway

### PR DESCRIPTION
**Pull request by mnwalker**
Who maintains this list? http://omnipay.thephpleague.com/gateways/third-party/

### CODE REVIEW

**Comment by judgej** [comment]
Amongst others, you :-)

**Comment by mnwalker** [comment]
The github page I am aware I can contribute to, thanks for merging the PR.
The omnipay website I can't see it pulled from a repository, only saw one for the phpleague website.
If I can update the main website can you point me in the right direction please?
Looking for this list/page http://omnipay.thephpleague.com/gateways/third-party/

**Comment by judgej** [comment]
It's all in the `gh-pages` branch:

https://github.com/thephpleague/omnipay/blob/gh-pages/gateways/third-party.md

**Comment by mnwalker** [comment]
Got it, thanks. - https://github.com/thephpleague/omnipay/pull/442

**Pull request merged**
