### PR TITLE
PayU gateway entegrated to omnipay.

### PR DESCRIPTION
**Pull request by efesaid**

### CODE REVIEW

**Comment by barryvdh** [comment]
You should create your own package,  you can add the link here.

**Comment by kayladnls** [comment]
@efesaid this looks great, and thank you for your work on this gateway, but @barryvdh is correct. You'll need to create your own package for this, and then am happy to link to it from the main Omnipay repo. 

If you need help with that, let me know. Thanks again!

**Comment by efesaid** [comment]
@kayladnls i created repo and added to packagist. can you please link with omnipay ? https://github.com/efesaid/omnipay-payu

**Comment by kayladnls** [comment]
Added it. Thank you!

**Comment by efesaid** [comment]
@kayladnls can you add it to composer.json too please?

**Comment by kayladnls** [comment]
Yup, sorry about the oversight.

**Pull request closed without merging**
