### PR TITLE
#261 declare transactionId

### PR DESCRIPTION
**Pull request by eileenmcnaughton**
In conjunction with https://github.com/thephpleague/omnipay/issues/261 & https://github.com/thephpleague/omnipay-common/pull/41

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
All passing now

**Comment by barryvdh** [comment]
'originating website' seems a bit unclear by my, perhaps better reflect that it's the reference set by the transactionId parameter when making the purchase request?

**Comment by eileenmcnaughton** [comment]
On the related patch I think we settled on merchant website - would that work for you?

**Comment by barryvdh** [comment]
Hmm, it still feels a bit off. It sounds like the transactionId is something 'externally set', while it's just a parameter that the developer sets and is hopefully return in the response.

**Comment by eileenmcnaughton** [comment]
Ok - so

$response->getTransactionId(); // the transactionId from the request, if available.

??

**Pull request merged**
