### PR TITLE
Make example expiry date in the future

### PR DESCRIPTION
**Pull request by TheoKouzelis**
Example throws an InvalidCreditCardException

### CODE REVIEW

**Comment by TheoKouzelis** [comment]
@judgej Is there some where else I need to create a PR to get it updated on website docs? http://omnipay.thephpleague.com/simple-example/

**Comment by judgej** [comment]
I'm not sure. I guess someone needs to run something to build the site, or maybe some tags need moving. I'll find out.

**Comment by TheoKouzelis** [comment]
Thanks

**Comment by judgej** [comment]
@TheoKouzelis Sorry, I didn't spot the problem - the PR is for the README file in the `master` branch. The "simple example" page you linked to is a markdown document in the `gh-pages` branch of the same repository. So the page you are looking at, is not the page that was updated. Your PR is merged, and is correct for where it was anyway, so that's good, but will also need to be changed here:

https://github.com/thephpleague/omnipay/blob/gh-pages/simple-example.md

**Pull request merged**
