### PR TITLE
[3.0] Use Container with autowire for factory/gateways

### PR DESCRIPTION
**Pull request by barryvdh**
This tries to remove all `new $class($client, $request)` stuff and replace it with autowiring, based on the [League Container](http://container.thephpleague.com/).

Pros:
 - More flexible, gateways require what they need in the constructor (because autowiring)
 - Central place to register the defaults
 - No more `new $class(..)` (code smell?)

This alone shouldn't affect most usage, except that I also removed the shortnames (and register/all/replace)

Pros:
 - No collisions, gateways can have their own namespace if they want.
 - Both IDE + developer can easily see what the actual gateways

Cons:
 - Longer to type? (But IDE typehints/imports anyway usually)
 - No list of 'registered' gateways, but for this specific case, this is easily done outside Omnipay

So old:
```php
use Omnipay\Omnipay;

$gateway = Omnipay::create('Stripe');
```

And new:
```php
use League\Omnipay\Omnipay;
use League\Omnipay\Stripe\StripeGateway;

$gateway = \League\Omnipay\Omnipay::create(StripeGateway::class);
```

### CODE REVIEW

**Comment by barryvdh** [comment]
ping @delatbabel  because you opposed the use of class names before ( in #274). Would this still be okay for you, as you can still use string names, expect only longer ones..

**Comment by delatbabel** [comment]
I think that one of the good things with OmniPay 2.0 method, which is:

    use Omnipay\Omnipay;
    $gateway = Omnipay::create('Stripe');

... is that I don't have to specifically change my code to initialise the Stripe gateway.  As soon as I have to specifically use the Stripe gateway to initialise it that means a code change each time I want to add a new gateway (admittedly I have to change composer.json anyway but that's not the point).

When I'm working in a multi-gateway environment that's more maintenance for me.

I guess this still fulfils my main criterion of having a Gateway->initialisation parameter mapping stored somewhere in the database but I would prefer not to have the explicit use statement.

**Comment by barryvdh** [comment]
But you can still do this:

```php
use League\Omnipay\Omnipay;
$gateway = \League\Omnipay\Omnipay::create('League\Omnipay\Stripe\StripeGateway');
```

The only thing that changes is that you store the class name instead of the short name?

**Comment by delatbabel** [comment]
Yes it would work, it's a bit more verbage but I'm OK with that.

**Comment by judgej** [comment]
Can anyone explain "autowire". What wires to what, and what part of that process happens automatically?

**Comment by barryvdh** [comment]
See http://container.thephpleague.com/auto-wiring/

The container has knowledge of some implementations (eg. which HttpClient there is etc), and instead of doen `new $class`, we ask the Container to resolve the class. With autowiring, it inspects the dependancies recursively, and tries to instantiate them as best as it can.

So it doesn't matter if the gateway requests HttpClient, ServerRequestFactory and some other class (or in which order), if the Container can resolve it, it instantiates them.

**Comment by judgej** [comment]
Ah, thanks. That makes it clearer. So it would not matter which [popular] PSR-7 client you happen to have installed, when you ask the container for a PSR-7 compatible client, that container (during its initialisation) has already got the installed client in there reader to do.

**Comment by barryvdh** [comment]
Yes, but we would have to think how to make this easily accessible to other frameworks/integrations.

In principe almost all containers support the container-interop interface, but we could create a GatewayFactory for Laravel for example, by providing a serviceprovider that uses the framework container instead of our own.

The main difference with before is that you just tell the container once which implementation you want to use for an interface, and it uses that for all instances.

**Comment by judgej** [comment]
Down the rabbit hole...in a good way :-) I can see where the two camps on container interop come from in the FIG - those that see an application having one container that all components use, vs a tree-like structure of containers that each component can bring along to the show as fragments.

**Comment by delatbabel** [comment]
The only caveat I can say about auto wiring and container resolution is that it's expensive in terms of processing time. Laravel uses container resolution extensively and profiling on the API components of our fairly large Laravel 5.1 application indicates that up to 30% of the total API round trip time is taken up in container resolution.

**Comment by ed-fruty** [comment]
For php 5.4 you can use something like *ClassNameTrait*
```php
// ClassNameTrait.php
trait ClassNameTrait
{
    public static function className()
    {
         return get_called_class();
    }
}

// Foo/Bar/PaymentGateway.php
class PaymentGateway
{
    use ClassNameTrait;
}

// example
use League\Omnipay\Omnipay;
use Foo\Bar\PaymentGateway;

$gateway = Omnipay::create(PaymentGateway::className());

```

**Comment by barryvdh** [comment]
Yeah but we're not supporting 5.4 in Omnipay v3, just 5.6+

**Comment by ed-fruty** [comment]
Sorry, I didn't pay attention.

**Comment by barryvdh** [comment]
Updated this by PRs from @ed-fruty

**Comment by barryvdh** [comment]
A thing I'm not really happy about, is that the Gateway is actually also a factory, so the Omnipay factory creates a different factory, which also uses the Container. 
Should we also have a 'MessageFactory', similar to GatewayFactory, to not depend on the Container directly?

**Pull request closed without merging**
